#### Get all users
GET http://localhost:3000/users

#### Get a specific user
GET http://localhost:3000/users/10
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsIm5hbWUiOiJBaG1lZCIsInVzZXJuYW1lIjoiRG9sYSIsImVtYWlsIjoiYWhtZWRlbGJpYWx5MTQ4QGdtYWlsLmNvbSIsImlhdCI6MTcwNDgwNDI4NiwiZXhwIjoxNzA0ODkwNjg2fQ.zFFDtZA3YXENurpabJkMnVWmBmZDkk1v5AQuB1Ohsec

#### Delete a specific user
DELETE http://localhost:3000/users/10
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsIm5hbWUiOiJBaG1lZCIsInVzZXJuYW1lIjoiRG9sYSIsImVtYWlsIjoiYWhtZWRlbGJpYWx5MTQ4QGdtYWlsLmNvbSIsImlhdCI6MTcwNDgwNDI4NiwiZXhwIjoxNzA0ODkwNjg2fQ.zFFDtZA3YXENurpabJkMnVWmBmZDkk1v5AQuB1Ohsec

#### Updatee a specific user
PATCH  http://localhost:3000/users/10
content-type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsIm5hbWUiOiJBaG1lZCIsInVzZXJuYW1lIjoiRG9sYSIsImVtYWlsIjoiYWhtZWRlbGJpYWx5MTQ4QGdtYWlsLmNvbSIsImlhdCI6MTcwNDgwNDI4NiwiZXhwIjoxNzA0ODkwNjg2fQ.zFFDtZA3YXENurpabJkMnVWmBmZDkk1v5AQuB1Ohsec

{
    "username": "Elbialy"
}

#### Signup a new user
POST http://localhost:3000/users/signup
content-type: application/json

{
    "name":"Ahmed",
    "username":"Dola",
    "email":"ahmedelbialy148@gmail.com",
    "password":"123456789"
}

#### Login
POST http://localhost:3000/users/login
content-type: application/json

{
    "email":"ahmedelbialy148@gmail.com",
    "password":"123456789"
}
